services:
  prisonersstrategy:
    image: ${DOCKER_REGISTRY-}prisonersstrategy
    build:
      context: .
      dockerfile: PrisonersStrategy/Dockerfile
    environment:
      - ITERATIONS_COUNT=100000
      - PRISONERS_EVEN_COUNT=1000
      - IS_BENCHMARK_MODE=false
